apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kgts2b0fd-nodejs
  janus-idp.io/tekton: kgts2b0fd-nodejs
  backstage.io/kubernetes-id: kgts2b0fd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kgts2b0fd-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
